services:
  opencode:
    image: ghcr.io/anomalyco/opencode:latest
    container_name: opencode
    user: "1000:1000"

    environment:
      HOME: /home/adolf

    stdin_open: true
    tty: true

    working_dir: /workspace

    volumes:
      - ../:/workspace
      - ../runtime:/home/adolf
      - ../agentes/agents:/home/adolf/.config/opencode/agents:ro
      - ./opencode.json:/home/adolf/.config/opencode/opencode.json:ro

    extra_hosts:
      - "host.docker.internal:host-gateway"
